## Numpy - Conceitos Introdutórios

É uma biblioteca de álgebra linear para python.

In [1]:
import numpy as np # Importa-se a biblioteca numpy

In [2]:
lista = [1,2,3] # Criando uma lista qualquer
lista # imprime a lista

[1, 2, 3]

In [3]:
np.array(lista) # Convertendo um array simples para um array numpy

array([1, 2, 3])

In [4]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz_numpy = np.array(matriz)
print(matriz_numpy)
print(matriz_numpy[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [5]:
np.arange(0,100,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5, 30. , 32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5, 50. , 52.5,
       55. , 57.5, 60. , 62.5, 65. , 67.5, 70. , 72.5, 75. , 77.5, 80. ,
       82.5, 85. , 87.5, 90. , 92.5, 95. , 97.5])

In [6]:
np.zeros(3) # criando um array de zeros

array([0., 0., 0.])

In [7]:
np.ones(5) # criando um array de 'um'

array([1., 1., 1., 1., 1.])

In [8]:
arr = np.zeros((5,5)) # Para o caso de uma matriz, passa-se o parâmetro para uma trupla
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## II - Malha

In [10]:
np.linspace(0,15,20)

array([ 0.        ,  0.78947368,  1.57894737,  2.36842105,  3.15789474,
        3.94736842,  4.73684211,  5.52631579,  6.31578947,  7.10526316,
        7.89473684,  8.68421053,  9.47368421, 10.26315789, 11.05263158,
       11.84210526, 12.63157895, 13.42105263, 14.21052632, 15.        ])

## III - Amostra aleatória - numpy.random

* Dados aleatórios simples

a) rand: Gera valores aleatórios entre 0 e 1, guardando-os em um array nxn.

In [11]:
np.random.rand(3,3)

array([[0.17613861, 0.1825507 , 0.72947992],
       [0.65457785, 0.60683839, 0.13635149],
       [0.04664077, 0.23297689, 0.56029037]])

b) randn: Gera valores aleatórios seguindo a distribuição normal padrão.

In [12]:
np.random.randn(5)

array([ 0.02536613, -0.95155504,  1.01041577, -2.3554722 ,  0.59941551])

c) Há outras formas de obter amostras aleatórios simples por meio dessa biblioteca, entre elas podemos citar: radint, random_integers, random_sample, random, ranf, sample, choice e bytes.

* Permutações

a) shuffle: modifica a sequência de forma misturada.



In [13]:
x = [3,4,5,6]
np.random.shuffle(x)
x

[4, 6, 5, 3]

b) permutation: permuta aleatoriamente uma sequência

In [14]:
np.random.permutation(x)

array([3, 5, 4, 6])

In [15]:
np.random.randint(1,25,15)

array([24, 16, 22,  7, 12,  3,  5, 18, 19, 13, 18,  8, 21, 24, 10])

### IV - Dando uma nova forma ao array sem alterar os seus dados.

In [16]:
# Convertendo a lista x em um array
x = np.array(x)
x

array([4, 6, 5, 3])

In [17]:
new_x = x.reshape((2,2)) # O array de 4 posições agora é uma matriz 2x2
new_x

array([[4, 6],
       [5, 3]])

In [18]:
new_x.shape

(2, 2)

In [19]:
x.min() # minimo via numpy

3

In [20]:
x.max()

6

In [21]:
x.argmax() # retorna o indice do valor máximo do array

1

In [22]:
x.argmin() # retorna o indice do valor mínimo do array

3

### V. Indexação e Fatiamento de arrays

In [23]:
x[3]

3

In [24]:
x[2:4]

array([5, 3])

In [25]:
x[:4]

array([4, 6, 5, 3])

In [26]:
x[1:]

array([6, 5, 3])

Essa indexação também pode ser utilizada para declarar arrays como, por exemplo, x[2:] = 100

##### Conceito 1: o exercício abaixo visa criar uma lista nova y a partir dos dados de outra lista e posteriormente atribuir novos valores a essa nova lista. Entretanto, para essa tarefa é necessário utilizar o comando .copy() com o objetivo de não alterar os valores da lista original.

In [27]:
y = x[:2].copy()
y

array([4, 6])

In [28]:
y[:2] = 100
y

array([100, 100])

In [29]:
x

array([4, 6, 5, 3])

##### Conceito 2: Obtendo fatiamentos de uma matriz


In [30]:
A = np.random.randn(5,5) # declaramos uma matriz 5x5 seguindo a distribuição normal
A

array([[ 0.83927489, -1.32718811,  0.0261188 , -0.1460032 ,  0.39851262],
       [ 0.34223946,  0.09398181, -0.36400634,  1.45830685,  0.15575494],
       [ 0.42168569,  0.1387864 ,  0.90911399,  0.66237992, -0.77716863],
       [-0.18953459,  1.21518903,  0.3735482 ,  0.08036239, -0.2571285 ],
       [ 0.89988211,  0.53497323,  0.5525803 , -1.01285668,  0.86418948]])

###### Exercício 1: A partir da matriz A, obtenha uma única matriz que contenha as seguintes informações: 

- Linhas 1, 2 e 3.
- Coluna 2 e 3.

In [31]:
A_mod = A[1:4,2:4]
A_mod

array([[-0.36400634,  1.45830685],
       [ 0.90911399,  0.66237992],
       [ 0.3735482 ,  0.08036239]])

#### Exercício 2: A partir matriz obtida no exercício 1, obtenha as posições e os valores negativos da matriz A.

In [32]:
bol = A_mod < 0
bol

array([[ True, False],
       [False, False],
       [False, False]])

In [33]:
A_mod[bol]

array([-0.36400634])

#### Exercício 3: Crie uma matriz 10x10 com números de 1 a 100 e em seguida, retorne quais valores são:

- pares
- ímpares

In [34]:
# Cria-se a matriz
a = np.arange(1,101,1).reshape((10,10))
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

- pares

In [35]:
verifica_pares = a % 2 == 0
a[verifica_pares]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

- impares

In [36]:
verifica_impares = a % 2 != 0
a[verifica_impares]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

#### Exercício 4: Repita o exercício para uma matriz 10000x10000.

In [37]:
# Cria-se a matriz
b = np.arange(1,100000001,1).reshape((10000,10000))
b

array([[        1,         2,         3, ...,      9998,      9999,
            10000],
       [    10001,     10002,     10003, ...,     19998,     19999,
            20000],
       [    20001,     20002,     20003, ...,     29998,     29999,
            30000],
       ...,
       [ 99970001,  99970002,  99970003, ...,  99979998,  99979999,
         99980000],
       [ 99980001,  99980002,  99980003, ...,  99989998,  99989999,
         99990000],
       [ 99990001,  99990002,  99990003, ...,  99999998,  99999999,
        100000000]])

In [38]:
verifica_pares = b % 2 == 0
b[verifica_pares]

array([        2,         4,         6, ...,  99999996,  99999998,
       100000000])

In [39]:
verifica_impares = b % 2 != 0
b[verifica_impares]

array([       1,        3,        5, ..., 99999995, 99999997, 99999999])

##### Exercício 5: Crie uma matriz dimensional superior qualquer. Recomendação: 5D ou mais

In [40]:
vetor = np.random.rand(10)
np.array(vetor,ndmin=5)

array([[[[[0.92594006, 0.30814763, 0.82250917, 0.61587907, 0.88905199,
           0.80125512, 0.91099433, 0.08912929, 0.7910404 , 0.38243728]]]]])

#### Exercício 6: Mostre um exemplo no qual pode ser utilizado a indexação negativa.

In [41]:
q = np.random.rand(3,3) 
print(q)

[[0.45818015 0.97569503 0.12076705]
 [0.49271454 0.56768102 0.18399929]
 [0.0727443  0.05067148 0.48317125]]


In [42]:
### Agora vamos selecionar a última linha da matriz

q[-1]

array([0.0727443 , 0.05067148, 0.48317125])

#### Exercício 7: Quais os tipos de dados usados em numpy?

int, boolean, float, complex float, unsigned integer, timedelta, datetime, object, string, unicode string e fixed chunk of memory for other type (void).

Fonte: https://www.w3schools.com/python/numpy_data_types.asp

### Iterando arrays

#### Exercício 8: Defina uma matriz 3x3 qualquer e itere-a.


In [43]:
m = np.random.randn(3,3)
m

array([[ 1.07122716,  0.48579743, -0.75811139],
       [-1.56234088,  2.53575409, -0.66465163],
       [ 2.0092347 , -0.19221822, -1.05738646]])

In [44]:
for i in m:
    print(i)

[ 1.07122716  0.48579743 -0.75811139]
[-1.56234088  2.53575409 -0.66465163]
[ 2.0092347  -0.19221822 -1.05738646]


#### Exercício 9: Repita o exercício anterior utilizando a função np.nditer().

In [45]:
for i in np.nditer(m):
    print(i)

1.071227159746845
0.48579743014118715
-0.7581113928390079
-1.5623408814717994
2.535754087878561
-0.664651625932036
2.0092347015763443
-0.1922182181264576
-1.057386456001086


#### Exercício 10: Utilize a matriz do exercício e enumere-a com os indices e os seus respectivos valores.

In [46]:
for i,x in np.ndenumerate(m):
    print(i,x)

(0, 0) 1.071227159746845
(0, 1) 0.48579743014118715
(0, 2) -0.7581113928390079
(1, 0) -1.5623408814717994
(1, 1) 2.535754087878561
(1, 2) -0.664651625932036
(2, 0) 2.0092347015763443
(2, 1) -0.1922182181264576
(2, 2) -1.057386456001086


### Pesquisa em Numpy

Uma das maneiras de fazer pesquisas em array no python é através do método where() contido na biblioteca Numpy. Esse método ao ser executado, retorna um conjunto de posições específicas do array parâmetro no qual é satisfeita a condição estabelecida. 

No trecho de código abaixo, define-se um vetor qualquer e em seguida o verificar determina quais as posições no qual o vetor possui um valor negativo.

In [47]:
vetor = np.array([1,2,4,-1,23,10,2,5,-11,7,9,-43,39])
verificador = np.where(vetor<0)
print(verificador)

(array([ 3,  8, 11], dtype=int64),)


#### Exercício 11: Utilizando o comando .randint(), gere um vetor contendo '0' e '1' de tamanho 100 e posteriormente, pesquise e printe os valores iguais a 1.

In [48]:
exerc11 = np.random.randint(2, size=100)
exerc11

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [49]:
verificador = np.where(exerc11==1)
print(verificador)

(array([ 0,  1,  2,  5,  6,  7,  8, 10, 13, 14, 15, 17, 19, 20, 21, 23, 24,
       25, 28, 29, 30, 31, 32, 34, 35, 37, 39, 40, 43, 45, 46, 48, 49, 50,
       51, 53, 54, 56, 58, 59, 60, 61, 62, 64, 65, 68, 69, 70, 72, 75, 76,
       78, 82, 83, 85, 88, 89, 90, 92, 93, 94, 96, 97, 98], dtype=int64),)


### Ordenação em Numpy

A operação de ordenação é realizada através da função np.sort().

#### Exercício 12: Gere números do tipo float de forma aleatória e, em seguida, ordene-os.

In [50]:
num = np.random.ranf(10)
num

array([0.60247994, 0.6903803 , 0.31737065, 0.92436851, 0.01899771,
       0.27711267, 0.77880209, 0.90539368, 0.82912392, 0.93613905])

In [51]:
print(np.sort(num))

[0.01899771 0.27711267 0.31737065 0.60247994 0.6903803  0.77880209
 0.82912392 0.90539368 0.92436851 0.93613905]


OBS.: Também é possível aplicar a função a variáveis do tipo string, boolean, inteiros.

### Filtro em Numpy

Essa operação pode ser implementada de variadas formas, uma delas o usuário pode criar um laço de repetição que percorre o conjunto de dados a fim de filtrar uma determinada informação. Outra opção que o usuário pode ter é a de comparar dois conjuntos de dados a fim de obter um subconjunto onde há uma harmonização entre ambos.

#### Exercício 13: O Conjunto de dados abaixo refere-se ao limite aprovado de clientes para transações bancárias em um banco. Logo, implemente de três formas diferentes onde aparecem os clientes com limite aprovado.

In [52]:
clientes = np.array(["Carlos","João","Maria","Alex","Lucas","Luana","Jéssica"])
clientes

array(['Carlos', 'João', 'Maria', 'Alex', 'Lucas', 'Luana', 'Jéssica'],
      dtype='<U7')

In [53]:
x =np.array([True,False,True,True,False,False,True])
x

array([ True, False,  True,  True, False, False,  True])

##### Forma 1

In [54]:
limite = clientes[x]
limite

array(['Carlos', 'Maria', 'Alex', 'Jéssica'], dtype='<U7')

###### Forma 2

In [55]:
for i in range (len(clientes)):
    if(x[i]==True): 
        print(clientes[i])

Carlos
Maria
Alex
Jéssica


##### Forma 3

In [56]:
filtro = x == True
novo_vetor = clientes[filtro]

print(novo_vetor)

['Carlos' 'Maria' 'Alex' 'Jéssica']


### Divisão de Matrizes em Numpy

Essa operação consiste em dividir um determinado array ou matriz em n partes de n dimensões.

In [57]:
array = np.random.rand(5)
array

array([0.80922766, 0.07339197, 0.692298  , 0.63064713, 0.64404504])

In [58]:
novo_array = np.array_split(array, 4)
novo_array

[array([0.80922766, 0.07339197]),
 array([0.692298]),
 array([0.63064713]),
 array([0.64404504])]

#### Exercício 14: Gere uma matriz 4x4 com valores que seguem a distribuição uniforme contínua e divida-a em 4 vetores contendo as colunas da matriz original.

In [59]:
# Gera-se a matriz
matriz = np.random.random_sample((4,4))
matriz

array([[0.96381894, 0.14949817, 0.74133784, 0.5797171 ],
       [0.36388414, 0.66892666, 0.74449837, 0.91068688],
       [0.63850951, 0.52644675, 0.20952553, 0.719797  ],
       [0.49787309, 0.56951184, 0.37060522, 0.52750831]])

In [60]:
# Dividi-se a matriz original em quatriz matrizes

nova_matriz = np.hsplit(matriz, 4)
nova_matriz 

[array([[0.96381894],
        [0.36388414],
        [0.63850951],
        [0.49787309]]),
 array([[0.14949817],
        [0.66892666],
        [0.52644675],
        [0.56951184]]),
 array([[0.74133784],
        [0.74449837],
        [0.20952553],
        [0.37060522]]),
 array([[0.5797171 ],
        [0.91068688],
        [0.719797  ],
        [0.52750831]])]