## Numpy - Conceitos Introdutórios

É uma biblioteca de álgebra linear para python.

In [46]:
import numpy as np # Importa-se a biblioteca numpy

In [2]:
lista = [1,2,3] # Criando uma lista qualquer
lista # imprime a lista

[1, 2, 3]

In [3]:
np.array(lista) # Convertendo um array simples para um array numpy

array([1, 2, 3])

In [4]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz_numpy = np.array(matriz)
print(matriz_numpy)
print(matriz_numpy[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [5]:
np.arange(0,100,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5, 30. , 32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5, 50. , 52.5,
       55. , 57.5, 60. , 62.5, 65. , 67.5, 70. , 72.5, 75. , 77.5, 80. ,
       82.5, 85. , 87.5, 90. , 92.5, 95. , 97.5])

In [6]:
np.zeros(3) # criando um array de zeros

array([0., 0., 0.])

In [7]:
np.ones(5) # criando um array de 'um'

array([1., 1., 1., 1., 1.])

In [8]:
arr = np.zeros((5,5)) # Para o caso de uma matriz, passa-se o parâmetro para uma trupla
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## II - Malha

In [10]:
np.linspace(0,15,20)

array([ 0.        ,  0.78947368,  1.57894737,  2.36842105,  3.15789474,
        3.94736842,  4.73684211,  5.52631579,  6.31578947,  7.10526316,
        7.89473684,  8.68421053,  9.47368421, 10.26315789, 11.05263158,
       11.84210526, 12.63157895, 13.42105263, 14.21052632, 15.        ])

## III - Amostra aleatória - numpy.random

* Dados aleatórios simples

a) rand: Gera valores aleatórios entre 0 e 1, guardando-os em um array nxn.

In [11]:
np.random.rand(3,3)

array([[0.40097417, 0.02183289, 0.83127721],
       [0.57771193, 0.41223296, 0.49581368],
       [0.54366152, 0.35153998, 0.18889302]])

b) randn: Gera valores aleatórios seguindo a distribuição normal padrão.

In [12]:
np.random.randn(5)

array([ 1.02309904, -0.39185042,  1.29851255,  0.85488673,  0.47897124])

c) Há outras formas de obter amostras aleatórios simples por meio dessa biblioteca, entre elas podemos citar: radint, random_integers, random_sample, random, ranf, sample, choice e bytes.

* Permutações

a) shuffle: modifica a sequência de forma misturada.



In [13]:
x = [3,4,5,6]
np.random.shuffle(x)
x

[5, 4, 3, 6]

b) permutation: permuta aleatoriamente uma sequência

In [14]:
np.random.permutation(x)

array([4, 6, 3, 5])

In [15]:
np.random.randint(1,25,15)

array([ 7,  3, 14, 14,  6, 20,  1, 11,  5, 16, 15,  4, 17, 20, 23])

### IV - Dando uma nova forma ao array sem alterar os seus dados.

In [16]:
# Convertendo a lista x em um array
x = np.array(x)
x

array([5, 4, 3, 6])

In [17]:
new_x = x.reshape((2,2)) # O array de 4 posições agora é uma matriz 2x2
new_x

array([[5, 4],
       [3, 6]])

In [18]:
new_x.shape

(2, 2)

In [19]:
x.min() # minimo via numpy

3

In [20]:
x.max()

6

In [21]:
x.argmax() # retorna o indice do valor máximo do array

3

In [22]:
x.argmin() # retorna o indice do valor mínimo do array

2

### V. Indexação e Fatiamento de arrays

In [23]:
x[3]

6

In [24]:
x[2:4]

array([3, 6])

In [25]:
x[:4]

array([5, 4, 3, 6])

In [26]:
x[1:]

array([4, 3, 6])

Essa indexação também pode ser utilizada para declarar arrays como, por exemplo, x[2:] = 100

##### Conceito 1: o exercício abaixo visa criar uma lista nova y a partir dos dados de outra lista e posteriormente atribuir novos valores a essa nova lista. Entretanto, para essa tarefa é necessário utilizar o comando .copy() com o objetivo de não alterar os valores da lista original.

In [27]:
y = x[:2].copy()
y

array([5, 4])

In [28]:
y[:2] = 100
y

array([100, 100])

In [29]:
x

array([5, 4, 3, 6])

##### Conceito 2: Obtendo fatiamentos de uma matriz


In [30]:
A = np.random.randn(5,5) # declaramos uma matriz 5x5 seguindo a distribuição normal
A

array([[ 0.81727994,  0.32141337, -0.27853536, -0.36155196, -0.48597877],
       [-0.29998633, -0.38028937, -0.51079064, -0.06953578,  1.46304007],
       [ 0.03319142,  1.20027927, -1.74765199,  1.45852526, -0.24805329],
       [ 1.37516347,  0.93679418,  0.68181155,  0.02889892,  0.97965763],
       [ 1.360192  ,  1.03527024, -1.23386269,  0.15255556, -0.42247949]])

###### Exercício 1: A partir da matriz A, obtenha uma única matriz que contenha as seguintes informações: 

- Linhas 1, 2 e 3.
- Coluna 2 e 3.

In [31]:
A_mod = A[1:4,2:4]
A_mod

array([[-0.51079064, -0.06953578],
       [-1.74765199,  1.45852526],
       [ 0.68181155,  0.02889892]])

#### Exercício 2: A partir matriz obtida no exercício 1, obtenha as posições e os valores negativos da matriz A.

In [32]:
bol = A_mod < 0
bol

array([[ True,  True],
       [ True, False],
       [False, False]])

In [33]:
A_mod[bol]

array([-0.51079064, -0.06953578, -1.74765199])

#### Exercício 3: Crie uma matriz 10x10 com números de 1 a 100 e em seguida, retorne quais valores são:

- pares
- ímpares

In [34]:
# Cria-se a matriz
a = np.arange(1,101,1).reshape((10,10))
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

- pares

In [35]:
verifica_pares = a % 2 == 0
a[verifica_pares]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

- impares

In [36]:
verifica_impares = a % 2 != 0
a[verifica_impares]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

#### Exercício 4: Repita o exercício para uma matriz 10000x10000. Posteriormente printe os possíveis resultados e comente sobre.

In [37]:
# Cria-se a matriz
b = np.arange(1,100000001,1).reshape((10000,10000))
b

array([[        1,         2,         3, ...,      9998,      9999,
            10000],
       [    10001,     10002,     10003, ...,     19998,     19999,
            20000],
       [    20001,     20002,     20003, ...,     29998,     29999,
            30000],
       ...,
       [ 99970001,  99970002,  99970003, ...,  99979998,  99979999,
         99980000],
       [ 99980001,  99980002,  99980003, ...,  99989998,  99989999,
         99990000],
       [ 99990001,  99990002,  99990003, ...,  99999998,  99999999,
        100000000]])

In [38]:
verifica_pares = b % 2 == 0
b[verifica_pares]

array([        2,         4,         6, ...,  99999996,  99999998,
       100000000])

In [39]:
verifica_impares = b % 2 != 0
b[verifica_impares]

array([       1,        3,        5, ..., 99999995, 99999997, 99999999])

##### Exercício 5: Crie uma matriz dimensional superior qualquer. Recomendação: 5D ou mais

In [40]:
vetor = np.random.rand(10)
np.array(vetor,ndmin=5)

array([[[[[0.58596157, 0.29370425, 0.17769543, 0.6655372 , 0.97967564,
           0.57952089, 0.36884107, 0.10076102, 0.24322361, 0.35606531]]]]])

#### Exercício 6: Mostre um exemplo no qual pode ser utilizado a indexação negativa.

In [41]:
q = np.random.rand(3,3) 
print(q)

[[0.2339378  0.13210225 0.52721502]
 [0.14556834 0.3409307  0.48011927]
 [0.12881566 0.08422052 0.50383934]]


In [42]:
### Agora vamos selecionar a última linha da matriz

q[-1]

array([0.12881566, 0.08422052, 0.50383934])

#### Exercício 7: Quais os tipos de dados usados em numpy?

int, boolean, float, complex float, unsigned integer, timedelta, datetime, object, string, unicode string e fixed chunk of memory for other type (void).

Fonte: https://www.w3schools.com/python/numpy_data_types.asp

### Iterando arrays

#### Exercício 8: Defina uma matriz 3x3 qualquer e itere-a.


In [51]:
m = np.random.randn(3,3)
m

array([[ 1.49164844, -1.47553812,  0.13982859],
       [ 1.12090322, -1.14692554, -1.49638414],
       [-0.74252257, -1.12489637, -0.07198669]])

In [53]:
for i in m:
    print(i)

[ 1.49164844 -1.47553812  0.13982859]
[ 1.12090322 -1.14692554 -1.49638414]
[-0.74252257 -1.12489637 -0.07198669]


#### Exercício 9: Repita o exercício anterior utilizando a função np.nditer().

In [54]:
for i in np.nditer(m):
    print(i)

1.4916484422814633
-1.4755381204323867
0.1398285938511407
1.120903217908213
-1.1469255374788063
-1.4963841407626304
-0.7425225686555832
-1.1248963713759768
-0.07198669195291775


#### Exercício 10: Utilize a matriz do exercício e enumere-a com os indices e os seus respectivos valores.

In [56]:
for i,x in np.ndenumerate(m):
    print(i,x)

(0, 0) 1.4916484422814633
(0, 1) -1.4755381204323867
(0, 2) 0.1398285938511407
(1, 0) 1.120903217908213
(1, 1) -1.1469255374788063
(1, 2) -1.4963841407626304
(2, 0) -0.7425225686555832
(2, 1) -1.1248963713759768
(2, 2) -0.07198669195291775
